name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.21, 1.22]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go }}"
      - name: Build
        run: |
          go vet .
          go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt